name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build binaries
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/ckube_linux_amd64 ./src/main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/ckube_darwin_amd64 ./src/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/ckube_windows_amd64.exe ./src/main.go
          GOOS=linux GOARCH=arm64 go build -o bin/ckube_linux_arm64 ./src/main.go
          chmod +x bin/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/ckube_linux_amd64
            bin/ckube_darwin_amd64
            bin/ckube_windows_amd64.exe
            bin/ckube_linux_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
